include: package:lint/analysis_options.yaml

analyzer:
  exclude: 
  - [build/**]
  - lib/*.config.dart
  - lib/**/*.g.dart
  - lib/**/*.freezed.dart
  - lib/**/*.gr.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
